### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by promumyhero** [ed-roh/inventory-management#4]
![image](https://github.com/user-attachments/assets/3c6c4ebb-6bc8-4a94-b976-11e2efbac61f)
can anyone help me with this error fetching, i have been 2 days debugging this thing? :(

**Comment by promumyhero** [comment]
expenses file 

`import {
  ExpenseByCategorySummary,
  useGetDashboardMetricsQuery,
} from "@/state/api";
import { TrendingUp } from "lucide-react";
import { Cell, Pie, PieChart, ResponsiveContainer } from "recharts";

type ExpenseSums = {
  [category: string]: number;
};

const colors = ["#00C49F", "#0088FE", "#FFBB28"];

const CardExpenseSummary = () => {
  const { data: dashboardMetrics, isLoading } = useGetDashboardMetricsQuery();

  const expenseSummary = dashboardMetrics?.expenseSummary[0];

  const expenseByCategorySummary =
    dashboardMetrics?.expenseByCategorySummary || [];

  const expenseSums = expenseByCategorySummary.reduce(
    (acc: ExpenseSums, item: ExpenseByCategorySummary) => {
      const category = item.category + "Expenses";
      const amount = parseInt(item.amount, 10);
      if (!acc[category]) acc[category] = 0;
      acc[category] += amount;
      return acc;
    },
    {}
  );

  const expenseCategories = Object.entries(expenseSums).map(
    ([name, value]) => ({
      name,
      value,
    })
  );

  const totalExpenses = expenseCategories.reduce(
    (acc, category: { value: number }) => acc + category.value,
    0
  );
  const formattedTotalExpenses = totalExpenses.toFixed(2);

  return (
    <div className="row-span-3 bg-white shadow-md rounded-2xl flex flex-col justify-between">
      {isLoading ? (
        <div className="m-5">Loading...</div>
      ) : (
        <>
          {/* HEADER */}
          <div>
            <h2 className="text-lg font-semibold mb-2 px-7 pt-5">
              Expense Summary
            </h2>
            <hr />
          </div>
          {/* BODY */}
          <div className="xl:flex justify-between pr-7">
            {/* CHART */}
            <div className="relative basis-3/5">
              <ResponsiveContainer width="100%" height={140}>
                <PieChart>
                  <Pie
                    data={expenseCategories}
                    innerRadius={50}
                    outerRadius={60}
                    fill="#8884d8"
                    dataKey="value"
                    nameKey="name"
                    cx="50%"
                    cy="50%"
                  >
                    {expenseCategories.map((entry, index) => (
                      <Cell
                        key={`cell-${index}`}
                        fill={colors[index % colors.length]}
                      />
                    ))}
                  </Pie>
                </PieChart>
              </ResponsiveContainer>
              <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-center basis-2/5">
                <span className="font-bold text-xl">
                  ${formattedTotalExpenses}
                </span>
              </div>
            </div>
            {/* LABELS */}
            <ul className="flex flex-col justify-around items-center xl:items-start py-5 gap-3">
              {expenseCategories.map((entry, index) => (
                <li
                  key={`legend-${index}`}
                  className="flex items-center text-xs"
                >
                  <span
                    className="mr-2 w-3 h-3 rounded-full"
                    style={{ backgroundColor: colors[index % colors.length] }}
                  ></span>
                  {entry.name}
                </li>
              ))}
            </ul>
          </div>
          {/* FOOTER */}
          <div>
            <hr />
            {expenseSummary && (
              <div className="mt-3 flex justify-between items-center px-7 mb-4">
                <div className="pt-2">
                  <p className="text-sm">
                    Average:{" "}
                    <span className="font-semibold">
                      ${expenseSummary.totalExpenses.toFixed(2)}
                    </span>
                  </p>
                </div>
                <span className="flex items-center mt-2">
                  <TrendingUp className="mr-2 text-green-500" />
                  30%
                </span>
              </div>
            )}
          </div>
        </>
      )}
    </div>
  );
};

export default CardExpenseSummary;`

**Comment by promumyhero** [comment]
nevermind, i found it. LOL,

**Comment by Brandonj171** [comment]
I am having the same error! What did you do to fix it?

**Comment by promumyhero** [comment]
can u show the error message? if The error code `42P01` (relation does not exist) indicates that the database is still missing the `Products` table. Since the migration history is locked due to the previous failure, let's go through some additional steps:

1. **Reset the Migration State** 
 If `npx prisma migrate reset` is not working due to the existing errors, try these steps to reset the migration state directly:
 
 ```bash
 npx prisma db push
 ```
 
 This command will push your Prisma schema to the database without applying migrations. It’s a quick way to sync your schema without depending on migration history.

2. **Verify the Database Schema** 
 After running `npx prisma db push`, check the database directly (via a PostgreSQL client or console) to see if the `Products` table now exists.

3. **Apply Migrations from Scratch** 
 If `db push` succeeds, clear out your migrations folder to avoid future conflicts and recreate the migrations:

 ```bash
 rm -rf prisma/migrations
 npx prisma migrate dev --name init
 ```

4. **Alternative: Drop and Recreate the Database** 
 If all else fails and if it's safe, consider dropping and recreating the database itself, then reapplying migrations.

Let me know if these steps help!


last time i just command npx prisma db push, without migrate again
